### PR TITLE
Adds gzip compression to the stream

### PR DESCRIPTION
**Pull request by IvanGuardado**

### CODE REVIEW

**Review by JvrBaena — APPROVED** [review]

**Comment by IvanGuardado** [comment]
Should we merge and deploy this? @aartiles

**Comment by aartiles** [comment]
didn't we rollback it?

**Comment by IvanGuardado** [comment]
I am not sure... I was on holidays...

**Comment by aartiles** [comment]
yes we did it, let's close by the moment as it was a bit unreliable

**Pull request closed without merging**
